"""
routers/export.py – EDL and CSV export endpoints.
Owned by KARTHIK. Sreedhar: do not edit this file.

Endpoints:
  GET /api/meetings/{id}/export.edl
  GET /api/meetings/{id}/export.csv
"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse

from backend.app import store
from backend.app.exporters.edl import build_edl
from backend.app.exporters.csv_export import build_csv

router = APIRouter(tags=["export"])


@router.get("/meetings/{meeting_id}/export.edl")
def export_edl(meeting_id: str):
    """
    Export approved, non-withdrawn items as a DaVinci Resolve EDL file.
    """
    transcript = store.get_transcript(meeting_id)
    if transcript is None:
        raise HTTPException(status_code=404, detail="Meeting not found")

    items = store.get_items(meeting_id)
    settings = store.get_settings(meeting_id)
    title = transcript.title or meeting_id

    edl_content = build_edl(items, settings, title)

    return PlainTextResponse(
        content=edl_content,
        media_type="text/plain",
        headers={
            "Content-Disposition": f'attachment; filename="{meeting_id}.edl"',
        },
    )


@router.get("/meetings/{meeting_id}/export.csv")
def export_csv(meeting_id: str):
    """
    Export approved, non-withdrawn items as a CSV file.
    """
    transcript = store.get_transcript(meeting_id)
    if transcript is None:
        raise HTTPException(status_code=404, detail="Meeting not found")

    items = store.get_items(meeting_id)
    settings = store.get_settings(meeting_id)

    csv_content = build_csv(items, settings)

    return PlainTextResponse(
        content=csv_content,
        media_type="text/csv",
        headers={
            "Content-Disposition": f'attachment; filename="{meeting_id}.csv"',
        },
    )
