"""
routers/ingest.py – Webhook + file import endpoints.
Owned by KARTHIK. Sreedhar: do not edit this file.

Endpoints:
  POST /api/webhooks/meetily   – receive signed Meetily webhook
  POST /api/meetings/import    – upload a transcript file
  GET  /api/meetily/status     – check Meetily API reachability
"""
import hashlib
import hmac
import sqlite3
import time
from contextlib import contextmanager
from typing import Generator

from fastapi import APIRouter, BackgroundTasks, HTTPException, Request, UploadFile, File

from backend.app import config, store
from backend.app.ingest import handle_summary_completed, parse_uploaded_transcript
from backend.app.pipeline import process_transcript

router = APIRouter(tags=["ingest"])


# ---------------------------------------------------------------------------
# Processed-events dedup table (same DB as DB_PATH)
# ---------------------------------------------------------------------------

@contextmanager
def _get_conn() -> Generator[sqlite3.Connection, None, None]:
    conn = sqlite3.connect(config.DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _init_processed_events() -> None:
    """Create processed_events table if not exists."""
    with _get_conn() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS processed_events (
                event_id TEXT PRIMARY KEY,
                received_at REAL NOT NULL
            )
        """)


def _is_duplicate(event_id: str) -> bool:
    """Check if an event_id has already been processed."""
    with _get_conn() as conn:
        row = conn.execute(
            "SELECT 1 FROM processed_events WHERE event_id = ?", (event_id,)
        ).fetchone()
        return row is not None


def _mark_processed(event_id: str) -> None:
    """Mark an event_id as processed."""
    with _get_conn() as conn:
        conn.execute(
            "INSERT OR IGNORE INTO processed_events (event_id, received_at) VALUES (?, ?)",
            (event_id, time.time()),
        )


# Initialize the table on import
_init_processed_events()

# Track last event received (for status endpoint)
_last_event_received: dict = {}


# ---------------------------------------------------------------------------
# Webhook signature verification
# ---------------------------------------------------------------------------

def _verify_signature(secret: str, timestamp: str, body: bytes, header_sig: str) -> bool:
    """
    Verify the Meetily webhook HMAC signature.

    Signature is computed over: {timestamp}.{body}
    Header format: sha256=<hex HMAC-SHA256>
    """
    if not secret or not timestamp or not header_sig:
        return False
    mac = hmac.new(
        secret.encode(),
        timestamp.encode() + b"." + body,
        hashlib.sha256,
    ).hexdigest()
    expected = f"sha256={mac}"
    return hmac.compare_digest(expected, header_sig)


# ---------------------------------------------------------------------------
# POST /api/webhooks/meetily
# ---------------------------------------------------------------------------

@router.post("/webhooks/meetily")
async def receive_webhook(request: Request, background_tasks: BackgroundTasks):
    """
    Receive a signed Meetily webhook event.

    1. Verify HMAC signature using MEETILY_WEBHOOK_SECRET
    2. Dedupe by event_id
    3. Return 200 quickly
    4. Process in background task
    """
    # Read raw body for signature verification
    body = await request.body()

    # Get signature headers
    signature = request.headers.get("X-Meetily-Signature", "")
    timestamp = request.headers.get("X-Meetily-Timestamp", "")

    # Verify signature
    if not _verify_signature(config.MEETILY_WEBHOOK_SECRET, timestamp, body, signature):
        raise HTTPException(status_code=401, detail="Invalid webhook signature")

    # Parse event
    import json
    try:
        event = json.loads(body)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    # Dedupe by event_id
    event_id = event.get("event_id", "")
    if not event_id:
        raise HTTPException(status_code=400, detail="Missing event_id")

    if _is_duplicate(event_id):
        return {"status": "duplicate", "event_id": event_id}

    # Mark as processed immediately (before background task)
    _mark_processed(event_id)

    # Track last event
    _last_event_received.update({
        "event_id": event_id,
        "event": event.get("event", ""),
        "received_at": time.time(),
    })

    # Process in background
    event_type = event.get("event", "")
    if event_type == "summary.completed":
        background_tasks.add_task(handle_summary_completed, event)

    return {"status": "accepted", "event_id": event_id}


# ---------------------------------------------------------------------------
# POST /api/meetings/import
# ---------------------------------------------------------------------------

@router.post("/meetings/import")
async def import_meeting(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
):
    """
    Upload a transcript file and run the pipeline on it.

    Accepts JSON (Meetily export or our format), Markdown, or plain text.
    """
    content = await file.read()
    filename = file.filename or "upload.txt"

    try:
        transcript = parse_uploaded_transcript(filename, content)
    except (ValueError, Exception) as e:
        raise HTTPException(status_code=400, detail=f"Failed to parse transcript: {e}")

    # Store transcript
    store.save_transcript(transcript, status="processing")

    # Run pipeline in background
    def _process():
        import logging
        import os
        from backend.app.llm import call_llm
        _log = logging.getLogger(__name__)
        try:
            # Generate title if missing
            if not transcript.title or transcript.title == "Untitled":
                text = " ".join([s.text for s in transcript.segments[:20]])
                if text.strip() and os.getenv("MOCK_LLM", "0") == "0":
                    sys_prompt = (
                        "You are an AI that generates a very short, concise title for a meeting transcript. "
                        "Rules:\n"
                        "1. MUST be under 50 characters.\n"
                        "2. ONLY output the title, no quotes, no extra text, no explanations.\n"
                        "3. Do not invent details not present in the text (No hallucinations).\n"
                        "4. If you cannot determine a title, output exactly 'Untitled Meeting'."
                    )
                    prompt = f"Generate a title based on this conversation snippet:\n{text}"
                    try:
                        title = call_llm(prompt, system=sys_prompt, json_mode=False)
                        title = title.strip(' "\'')
                        if title and len(title) <= 60:
                            store.update_meeting_title(transcript.meeting_id, title)
                    except Exception as e:
                        _log.error("Failed to generate title: %s", e)

            settings = store.get_settings(transcript.meeting_id)
            items = process_transcript(transcript, settings)
            _log.info("Pipeline produced %d items for %s", len(items), transcript.meeting_id)
            if items:
                store.save_items(transcript.meeting_id, items)
                _log.info("Saved %d items for %s", len(items), transcript.meeting_id)
            else:
                _log.warning("Pipeline returned 0 items for %s", transcript.meeting_id)
                
            store.update_meeting_status(transcript.meeting_id, "completed")
        except Exception as exc:
            _log.exception("Background _process failed for %s: %s", transcript.meeting_id, exc)
            store.update_meeting_status(transcript.meeting_id, "failed")

    background_tasks.add_task(_process)

    return {
        "status": "processing",
        "meeting_id": transcript.meeting_id,
        "segments": len(transcript.segments),
    }


# ---------------------------------------------------------------------------
# GET /api/meetily/status
# ---------------------------------------------------------------------------

@router.get("/meetily/status")
def meetily_status():
    """
    Check whether the Meetily API is reachable and if a webhook is registered.
    """
    from backend.app import meetily_client

    reachable = meetily_client.is_reachable()
    webhook_registered = False
    webhooks = []

    if reachable:
        try:
            webhooks = meetily_client.list_webhooks()
            # Check if any webhook points to our receiver
            our_url = "http://127.0.0.1:8000/api/webhooks/meetily"
            for wh in (webhooks if isinstance(webhooks, list) else []):
                if isinstance(wh, dict) and wh.get("url", "").rstrip("/") == our_url.rstrip("/"):
                    webhook_registered = True
                    break
        except Exception:
            pass

    result = {
        "meetily_reachable": reachable,
        "webhook_registered": webhook_registered,
    }

    if _last_event_received:
        result["last_event"] = _last_event_received

    return result
