"""
routers/ingest.py – Webhook + file import endpoints.
Owned by KARTHIK. Sreedhar: do not edit this file.
"""
from fastapi import APIRouter

router = APIRouter(tags=["ingest"])


# POST /api/webhooks/meetily
# POST /api/meetings/import   (multipart file)
# GET  /api/meetily/status
