"""
routers/privacy.py – Safe-transcript redaction endpoint (stretch goal).
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

GET /api/meetings/{id}/safe-transcript
  -> Returns the transcript with PII redacted plus a list of what was hidden.
  -> The mapping (placeholder -> original) is NOT included in the response.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from backend.app import store
from backend.app.redaction import redact_transcript

router = APIRouter(tags=["privacy"])


class SafeTranscriptResponse(BaseModel):
    meeting_id: str
    title: str | None = None
    redacted_segments: list[dict]
    hidden_items: list[str]   # human-readable list, e.g. ["Email 1", "Phone 1"]
    note: str = (
        "PII has been removed. The mapping is retained only on the local machine "
        "and is never transmitted."
    )


@router.get("/api/meetings/{meeting_id}/safe-transcript", response_model=SafeTranscriptResponse)
def get_safe_transcript(meeting_id: str) -> SafeTranscriptResponse:
    """
    Return a redacted copy of the meeting transcript with PII replaced by
    consistent placeholders. The placeholder-to-original mapping is kept
    only in server memory for this request and is never serialised.

    Hidden item categories returned: Email, Phone, Amount, Person.
    """
    transcript = store.get_transcript(meeting_id)
    if transcript is None:
        raise HTTPException(status_code=404, detail=f"Meeting '{meeting_id}' not found.")

    redacted_t, mapping = redact_transcript(transcript)

    # Build a human-readable list of what was hidden (placeholder labels only)
    hidden_items = sorted(mapping.keys())

    redacted_segments = [
        {
            "start_sec": seg.start_sec,
            "end_sec": seg.end_sec,
            "speaker": seg.speaker,
            "text": seg.text,
        }
        for seg in redacted_t.segments
    ]

    return SafeTranscriptResponse(
        meeting_id=meeting_id,
        title=redacted_t.title,
        redacted_segments=redacted_segments,
        hidden_items=hidden_items,
    )
