"""
exporters/csv_export.py – CSV export of approved feedback items.
Owned by KARTHIK. Sreedhar: do not edit this file.

Export includes only items with status == "approved" and withdrawn == False.
Columns: id, timecode, type, category, priority, note, quote, speaker, confidence, status, version
"""
import csv
import io

from backend.app.exporters.timecode import seconds_to_timecode
from backend.app.models import FeedbackItem, ProjectSettings


def build_csv(items: list[FeedbackItem], settings: ProjectSettings) -> str:
    """
    Build a CSV string of approved, non-withdrawn feedback items.

    Columns: id, timecode, type, category, priority, note, quote, speaker,
             confidence, status, version

    Args:
        items:    Full list of FeedbackItems for a meeting.
        settings: ProjectSettings (fps, start_timecode, etc.).

    Returns:
        A CSV string (with header row) ready to write to a .csv file.
    """
    # Filter: only approved and non-withdrawn
    exportable = [
        item for item in items
        if item.status == "approved" and not item.withdrawn
    ]

    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow([
        "id", "timecode", "type", "category", "priority",
        "note", "quote", "speaker", "confidence", "status", "version",
    ])

    for item in exportable:
        # Compute timecode
        if item.is_global or item.anchor_sec is None:
            tc = settings.start_timecode
        else:
            tc = seconds_to_timecode(item.anchor_sec, settings.fps, settings.start_timecode)

        writer.writerow([
            item.id,
            tc,
            item.type,
            item.category,
            item.priority,
            item.note,
            item.quote,
            item.speaker or "",
            f"{item.confidence:.2f}",
            item.status,
            settings.version_label,
        ])

    return output.getvalue()
