"""
exporters/csv_export.py – CSV export of approved feedback items.
Owned by KARTHIK. Sreedhar: do not edit this file.

Export includes only items with status == "approved" and withdrawn == False.
"""
from backend.app.models import FeedbackItem, ProjectSettings


def build_csv(items: list[FeedbackItem], settings: ProjectSettings) -> str:
    """
    Build a CSV string of approved, non-withdrawn feedback items.

    Columns (suggested): timecode, type, category, priority, quote, note, confidence.

    Args:
        items:    Full list of FeedbackItems for a meeting.
        settings: ProjectSettings (fps, start_timecode, etc.).

    Returns:
        A CSV string (with header row) ready to write to a .csv file.
    """
    raise NotImplementedError
