"""
exporters/edl.py – DaVinci Resolve color-coded EDL marker export.
Owned by KARTHIK. Sreedhar: do not edit this file.

Export includes only items with status == "approved" and withdrawn == False.

DaVinci Resolve imports markers from an EDL whose comment lines look like:
  |C:ResolveColorRed |M:marker note |D:1
after each event line.

Colors: change = Red, question = Blue, approval = Green.
Global notes go at the start timecode with "[GLOBAL]" in the name.
Marker time = start_timecode + anchor_sec, in frames.
"""
from backend.app.exporters.timecode import seconds_to_timecode, seconds_to_frames, _parse_timecode, _frames_to_timecode
from backend.app.models import FeedbackItem, ProjectSettings

# Resolve color mapping
COLOR_MAP = {
    "change": "Red",
    "question": "Blue",
    "approval": "Green",
}


def build_edl(items: list[FeedbackItem], settings: ProjectSettings, title: str) -> str:
    """
    Build a CMX 3600 EDL string with colour-coded markers for DaVinci Resolve.

    Only approved, non-withdrawn items are included.
    Marker colours: change=Red, question=Blue, approval=Green.

    Args:
        items:    Full list of FeedbackItems for a meeting.
        settings: ProjectSettings (fps, start_timecode, etc.).
        title:    Meeting / project title for the EDL header.

    Returns:
        A CMX 3600 EDL string ready to write to a .edl file.
    """
    fps = settings.fps
    version = settings.version_label

    # Filter: only approved and non-withdrawn
    exportable = [
        item for item in items
        if item.status == "approved" and not item.withdrawn
    ]

    # EDL header
    edl_title = f"{title} - {version}" if title else version
    lines = [
        f"TITLE: {edl_title}",
        f"FCM: NON-DROP FRAME",
        "",
    ]

    event_num = 1

    for item in exportable:
        # Determine timecode
        if item.is_global or item.anchor_sec is None:
            # Global items go at start timecode (0 seconds from start)
            tc = settings.start_timecode
            marker_name = f"[GLOBAL] {version} - {item.note}"
        else:
            tc = seconds_to_timecode(item.anchor_sec, fps, settings.start_timecode)
            marker_name = f"{version} - {item.note}"

        color = COLOR_MAP.get(item.type, "Red")

        # CMX 3600 event line
        # Format: EVENT_NUM  REEL  TRACK  TRANSITION  SRC_IN  SRC_OUT  REC_IN  REC_OUT
        event_line = f"{event_num:03d}  001      V     C        {tc} {tc} {tc} {tc}"
        # Resolve marker comment line
        # Format: |C:ResolveColor<Color> |M:<marker note> |D:1
        comment_line = f"|C:ResolveColor{color} |M:{marker_name} |D:1"

        lines.append(event_line)
        lines.append(comment_line)
        lines.append("")

        event_num += 1

    return "\n".join(lines)
