"""
exporters/edl.py – DaVinci Resolve color-coded EDL marker export.
Owned by KARTHIK. Sreedhar: do not edit this file.

Export includes only items with status == "approved" and withdrawn == False.

DaVinci Resolve imports markers from an EDL whose comment lines look like:
  |C:ResolveColorRed |M:marker note |D:1
after each event line.

Colors: change = Red, question = Blue, approval = Green.
Global notes go at the start timecode with "[GLOBAL]" in the name.
Marker time = start_timecode + anchor_sec, in frames.
"""
from backend.app.exporters.timecode import seconds_to_timecode, seconds_to_frames, _parse_timecode, _frames_to_timecode
from backend.app.models import FeedbackItem, ProjectSettings

# Resolve color mapping
COLOR_MAP = {
    "change": "Red",
    "question": "Blue",
    "approval": "Green",
}


def build_edl(
    items: list[FeedbackItem],
    settings: ProjectSettings,
    title: str,
    edit_instructions: list[dict] | None = None,
) -> str:
    """
    Build a CMX 3600 EDL string with colour-coded markers for DaVinci Resolve.

    Only approved, non-withdrawn items are included.
    Marker colours: change=Red, question=Blue, approval=Green.
    """
    fps = settings.fps
    version = settings.version_label

    # Build edit instruction lookup map: item_id -> instruction dict
    edits_by_item = {}
    if edit_instructions:
        for inst in edit_instructions:
            if inst.get("status") in ("approved", "pending"):
                edits_by_item[inst["item_id"]] = inst

    # Filter: only approved and non-withdrawn
    exportable = [
        item for item in items
        if item.status == "approved" and not item.withdrawn
    ]
    exportable.sort(key=lambda item: (not item.is_global, item.anchor_sec or 0.0))

    # EDL header
    edl_title = f"{title} - {version}" if title else version
    lines = [
        f"TITLE: {edl_title}",
        f"FCM: NON-DROP FRAME",
        "",
    ]

    event_num = 1

    for item in exportable:
        inst = edits_by_item.get(item.id)
        effect_prefix = ""
        if inst:
            eff_name = inst.get("effect", "").upper().replace("_", " ")
            target = inst.get("target_entity", "")
            s_sec = inst.get("start_sec", 0.0)
            e_sec = inst.get("end_sec", 0.0)
            
            m_s, ss_s = int(s_sec // 60), int(s_sec % 60)
            m_e, ss_e = int(e_sec // 60), int(e_sec % 60)
            tc_range = f"{m_s}:{ss_s:02d}-{m_e}:{ss_e:02d}"
            
            target_str = f" {target}" if target else ""
            effect_prefix = f"[{eff_name}]{target_str} {tc_range} "

        # Determine timecode
        if item.is_global or item.anchor_sec is None:
            tc = settings.start_timecode
            marker_name = f"{effect_prefix}[GLOBAL] {version} - {item.note}".strip()
        else:
            tc = seconds_to_timecode(item.anchor_sec, fps, settings.start_timecode)
            marker_name = f"{effect_prefix}{version} - {item.note}".strip()

        color = COLOR_MAP.get(item.type, "Red")

        # CMX 3600 event line
        event_line = f"{event_num:03d}  001      V     C        {tc} {tc} {tc} {tc}"
        # Resolve marker comment line
        comment_line = f"|C:ResolveColor{color} |M:{marker_name} |D:1"

        lines.append(event_line)
        lines.append(comment_line)
        lines.append("")

        event_num += 1

    return "\n".join(lines)

