"""
exporters/edl.py – DaVinci Resolve color-coded EDL marker export.
Owned by KARTHIK. Sreedhar: do not edit this file.

Export includes only items with status == "approved" and withdrawn == False.
"""
from backend.app.models import FeedbackItem, ProjectSettings


def build_edl(items: list[FeedbackItem], settings: ProjectSettings, title: str) -> str:
    """
    Build a CMX 3600 EDL string with colour-coded markers for DaVinci Resolve.

    Only approved, non-withdrawn items are included.
    Marker colours suggested: change=Red, question=Blue, approval=Green.

    Args:
        items:    Full list of FeedbackItems for a meeting.
        settings: ProjectSettings (fps, start_timecode, etc.).
        title:    Meeting / project title for the EDL header.

    Returns:
        A CMX 3600 EDL string ready to write to a .edl file.
    """
    raise NotImplementedError
