"""
exporters/timecode.py – Timecode utilities shared by EDL and CSV exporters.
Owned by KARTHIK. Sreedhar: do not edit this file.

Non-drop-frame SMPTE timecodes: HH:MM:SS:FF
"""


def _parse_timecode(tc: str, fps: float) -> int:
    """Parse a timecode string HH:MM:SS:FF into a total frame count."""
    parts = tc.replace(";", ":").split(":")
    if len(parts) != 4:
        raise ValueError(f"Invalid timecode format: {tc!r}, expected HH:MM:SS:FF")
    hh, mm, ss, ff = (int(p) for p in parts)
    fps_int = round(fps)
    return ((hh * 3600 + mm * 60 + ss) * fps_int) + ff


def _frames_to_timecode(total_frames: int, fps: float) -> str:
    """Convert a total frame count to HH:MM:SS:FF."""
    fps_int = round(fps)
    if fps_int <= 0:
        raise ValueError(f"fps must be positive, got {fps}")
    ff = total_frames % fps_int
    total_seconds = total_frames // fps_int
    ss = total_seconds % 60
    total_minutes = total_seconds // 60
    mm = total_minutes % 60
    hh = total_minutes // 60
    return f"{hh:02d}:{mm:02d}:{ss:02d}:{ff:02d}"


def seconds_to_frames(seconds: float, fps: float) -> int:
    """Convert seconds to a frame count (floor)."""
    return int(seconds * fps)


def frames_to_seconds(frames: int, fps: float) -> float:
    """Convert a frame count to seconds."""
    return frames / fps


def seconds_to_timecode(
    seconds: float, fps: float, start_timecode: str = "01:00:00:00"
) -> str:
    """
    Convert a floating-point seconds value to a SMPTE timecode string HH:MM:SS:FF,
    offset by start_timecode.

    Args:
        seconds:         Time in seconds from the start of the video.
        fps:             Frames per second.
        start_timecode:  Timeline start timecode, e.g. "01:00:00:00".

    Returns:
        Timecode string in HH:MM:SS:FF format.
    """
    start_frames = _parse_timecode(start_timecode, fps)
    video_frames = seconds_to_frames(seconds, fps)
    total_frames = start_frames + video_frames
    return _frames_to_timecode(total_frames, fps)


def timecode_to_seconds(
    timecode: str, fps: float, start_timecode: str = "01:00:00:00"
) -> float:
    """
    Convert a SMPTE timecode string back to seconds, removing the start_timecode offset.

    Args:
        timecode:        Timecode string HH:MM:SS:FF.
        fps:             Frames per second.
        start_timecode:  Timeline start timecode.

    Returns:
        Time in seconds from the start of the video.
    """
    tc_frames = _parse_timecode(timecode, fps)
    start_frames = _parse_timecode(start_timecode, fps)
    video_frames = tc_frames - start_frames
    return frames_to_seconds(video_frames, fps)
