"""
exporters/timecode.py – Timecode utilities shared by EDL and CSV exporters.
Owned by KARTHIK. Sreedhar: do not edit this file.
"""


def seconds_to_timecode(seconds: float, fps: float, start_timecode: str = "01:00:00:00") -> str:
    """
    Convert a floating-point seconds value to a SMPTE timecode string HH:MM:SS:FF,
    offset by start_timecode.

    Args:
        seconds:         Time in seconds from the start of the video.
        fps:             Frames per second.
        start_timecode:  Timeline start timecode, e.g. "01:00:00:00".

    Returns:
        Timecode string in HH:MM:SS:FF format.
    """
    raise NotImplementedError
