"""
anchoring.py – Pure, deterministic anchoring of feedback items to video timecodes.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Extension point for vision: see FrameGrounder Protocol below.
"""
from __future__ import annotations

import logging
import re
from typing import Protocol, runtime_checkable

from backend.app.models import FeedbackItem, ProjectSettings

logger = logging.getLogger(__name__)


# ── FrameGrounder Protocol (not implemented – future vision plug-in) ──────────

@runtime_checkable
class FrameGrounder(Protocol):
    """
    Extension point for future video-frame analysis.

    A FrameGrounder can take a feedback quote and a rough time range and
    return the precise video frame (in seconds) that best matches the
    described visual moment.

    Implement this protocol in a separate module and pass an instance to
    anchor_items() via `grounder=` to activate vision-based anchoring.

    This is intentionally NOT implemented for the MVP.
    See Context.md section 1: "Extension point for vision: FrameGrounder".
    """

    def ground(
        self,
        quote: str,
        anchor_hint_sec: float | None,
        *,
        meeting_id: str,
    ) -> float | None:
        """
        Return a refined anchor in seconds, or None if unable to ground.

        Args:
            quote:           The verbatim client quote.
            anchor_hint_sec: Coarse anchor from time-parsing / meeting clock.
            meeting_id:      The meeting/project identifier.
        """
        ...


# ── Spoken-time parser ────────────────────────────────────────────────────────

# word-number lookup for up to 59 (covers minutes and seconds)
_WORD_NUMS: dict[str, int] = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
    "eleven": 11, "twelve": 12, "thirteen": 13, "fourteen": 14,
    "fifteen": 15, "sixteen": 16, "seventeen": 17, "eighteen": 18,
    "nineteen": 19, "twenty": 20, "thirty": 30, "forty": 40,
    "fifty": 50,
}

def _word_to_int(s: str) -> int | None:
    """Convert a single word-number to int, or return None."""
    return _WORD_NUMS.get(s.lower().strip())


def _compound_word_to_sec(text: str) -> float | None:
    """
    Try to parse compound spoken time like "two minutes forty" or
    "twenty seconds" from a short phrase.
    Returns seconds, or None.
    """
    text = text.lower().strip()
    # Pattern: "<minutes_word> minute[s] [and] <seconds_word> [second[s]]"
    m = re.match(
        r"^(\w+)\s+minutes?\s+(?:and\s+)?(\w+)(?:\s+seconds?)?$", text
    )
    if m:
        mins = _word_to_int(m.group(1))
        secs = _word_to_int(m.group(2))
        if mins is not None and secs is not None:
            return mins * 60 + secs

    # Pattern: "<minutes_word> minute[s]" only
    m = re.match(r"^(\w+)\s+minutes?$", text)
    if m:
        mins = _word_to_int(m.group(1))
        if mins is not None:
            return float(mins * 60)

    # Pattern: "<seconds_word> second[s]"
    m = re.match(r"^(\w+)\s+seconds?$", text)
    if m:
        secs = _word_to_int(m.group(1))
        if secs is not None:
            return float(secs)

    return None


# Patterns tried in order; first match wins.
# Each pattern must produce named groups: at minimum one of (h, m, s, phrase).
_PATTERNS: list[tuple[str, str]] = [
    # HH:MM:SS  e.g. "01:42:10"
    ("hms_colon",  r"\b(?P<h>\d{1,2}):(?P<m>\d{2}):(?P<s>\d{2})\b"),
    # M:SS or MM:SS  e.g. "1:24", "01:05"
    ("ms_colon",   r"\b(?P<m>\d{1,2}):(?P<s>\d{2})\b"),
    # "at 30 seconds" / "at 90 seconds"
    ("at_seconds", r"\bat\s+(?P<s>\d+)\s+seconds?\b"),
    # "at five seconds" / "at the five-second mark"
    ("at_seconds_word", r"\bat\s+(?:the\s+)?(?P<phrase>zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)[ -]+seconds?\b"),
    ("seconds_mark_digit", r"\b(?:at\s+(?:the\s+)?)?(?P<s>\d+)[ -]+seconds?\s+mark\b"),
    ("seconds_mark_word", r"\b(?:at\s+(?:the\s+)?)?(?P<phrase>zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)[ -]+seconds?\s+mark\b"),
    # "at the X minute mark" / "around the X minute mark"
    ("minute_mark_digit", r"\b(?:around\s+the\s+|at\s+the\s+)?(?P<m>\d+)\s+minute\s+mark\b"),
    # "X minutes in" / "X minute in"
    ("minutes_in_digit", r"\b(?P<m>\d+)\s+minutes?\s+in\b"),
    # "one minute in" / "two minutes in" (word numbers)
    ("minutes_in_word", r"\b(?P<phrase>(?:zero|one|two|three|four|five|six|seven|eight|nine|ten"
                         r"|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen"
                         r"|nineteen|twenty|thirty|forty|fifty)\s+minutes?\s+in)\b"),
    # "around the two minute mark" (word numbers)
    ("minute_mark_word", r"\b(?:around\s+the\s+|at\s+the\s+)?(?P<phrase>"
                          r"(?:zero|one|two|three|four|five|six|seven|eight|nine|ten"
                          r"|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen"
                          r"|nineteen|twenty|thirty|forty|fifty)\s+minute\s+mark)\b"),
    # "two minutes forty" / "one minute fifteen"
    ("compound_words", r"\b(?P<phrase>(?:zero|one|two|three|four|five|six|seven|eight|nine|ten"
                        r"|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen"
                        r"|nineteen|twenty|thirty|forty|fifty)"
                        r"\s+minutes?\s+(?:and\s+)?(?:zero|one|two|three|four|five|six|seven"
                        r"|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen"
                        r"|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)"
                        r"(?:\s+seconds?)?)\b"),
]


def parse_spoken_time(text: str) -> float | None:
    """
    Scan *text* for a spoken time reference and return seconds as float,
    or None if no recognisable reference is found.

    Handles (examples):
      "1:24"              -> 84.0
      "01:42:10"          -> 6130.0
      "at 30 seconds"     -> 30.0
      "one minute in"     -> 60.0
      "two minutes forty" -> 160.0
      "around the 2 minute mark" -> 120.0
    """
    lower = text.lower()
    for name, pattern in _PATTERNS:
        m = re.search(pattern, lower, re.IGNORECASE)
        if not m:
            continue
        gd = m.groupdict()

        if name == "hms_colon":
            return int(gd["h"]) * 3600 + int(gd["m"]) * 60 + int(gd["s"])

        if name == "ms_colon":
            return int(gd["m"]) * 60 + int(gd["s"])

        if name == "at_seconds":
            return float(gd["s"])

        if name in ("seconds_mark_digit",):
            return float(gd["s"])

        if name in ("at_seconds_word", "seconds_mark_word"):
            value = _word_to_int(gd["phrase"].split()[0])
            if value is not None:
                return float(value)

        if name in ("minute_mark_digit", "minutes_in_digit"):
            return float(int(gd["m"]) * 60)

        if name in ("minutes_in_word", "minute_mark_word"):
            phrase = gd["phrase"]
            # strip trailing "in" or "mark" — phrase already contains "minute(s)"
            phrase = re.sub(r"\s*(in|mark)\s*$", "", phrase).strip()
            # phrase is now e.g. "one minute" or "two minutes"; parse directly
            result = _compound_word_to_sec(phrase)
            if result is not None:
                return result

        if name == "compound_words":
            phrase = gd["phrase"]
            result = _compound_word_to_sec(phrase)
            if result is not None:
                return result

    return None


# ── Main anchor function ──────────────────────────────────────────────────────

def anchor_items(
    items: list[FeedbackItem],
    settings: ProjectSettings,
    *,
    grounder: FrameGrounder | None = None,  # reserved for future vision plug-in
) -> list[FeedbackItem]:
    """
    Compute ``anchor_sec`` (video time in seconds) for each FeedbackItem.

    This is a **pure function** – no LLM, no I/O. Safe to call multiple times
    when settings (sync_offset_sec, lookback_sec) change.

    Algorithm:
      1. If spoken_timecode_sec is set:
             anchor_sec    = spoken_timecode_sec
             anchor_source = "spoken_timecode"
      2. Else if is_global:
             anchor_sec    = None
             anchor_source = "none"
      3. Else:
             anchor_sec    = max(0, segment_start_sec + sync_offset_sec - lookback_sec)
             anchor_source = "meeting_clock"

    needs_review is set True when:
      - confidence < 0.7, OR
      - anchor_source != "spoken_timecode", OR
      - is_global is True

    Args:
        items:    FeedbackItems returned by extract_feedback.
        settings: Current ProjectSettings for this meeting.
        grounder: Optional FrameGrounder for vision-based refinement (MVP: unused).

    Returns:
        A **new** list of FeedbackItems with anchor_sec and anchor_source set.
        The input list is NOT mutated.
    """
    result: list[FeedbackItem] = []

    for item in items:
        # Work on a copy so we don't mutate the caller's objects
        updated = item.model_copy(deep=True)

        if updated.spoken_timecode_sec is not None:
            # Highest-confidence anchor: client said an explicit timecode
            updated.anchor_sec = updated.spoken_timecode_sec
            updated.anchor_source = "spoken_timecode"

        elif updated.is_global:
            # Global note has no meaningful single anchor point
            updated.anchor_sec = None
            updated.anchor_source = "none"

        else:
            # Fall back to meeting clock with sync offset and lookback
            raw = (
                updated.segment_start_sec
                + settings.sync_offset_sec
                - settings.lookback_sec
            )
            updated.anchor_sec = max(0.0, raw)
            updated.anchor_source = "meeting_clock"

        # ── needs_review heuristic ───────────────────────────────────────────
        updated.needs_review = (
            updated.confidence < 0.7
            or updated.anchor_source != "spoken_timecode"
            or updated.is_global
        )

        # ── Optional vision grounding (future; not active in MVP) ────────────
        if grounder is not None and updated.anchor_sec is not None:
            try:
                refined = grounder.ground(
                    updated.quote,
                    updated.anchor_sec,
                    meeting_id=updated.meeting_id,
                )
                if refined is not None:
                    updated.anchor_sec = refined
            except Exception:  # noqa: BLE001
                logger.warning("FrameGrounder raised an exception; ignoring.", exc_info=True)

        result.append(updated)

    return result
