"""
anchoring.py – Pure, deterministic anchoring of feedback items to video timecodes.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Extension point for vision: FrameGrounder (see Context.md section 1).
"""
from backend.app.models import FeedbackItem, ProjectSettings


def anchor_items(
    items: list[FeedbackItem], settings: ProjectSettings
) -> list[FeedbackItem]:
    """
    Compute `anchor_sec` (video time in seconds) for each FeedbackItem.

    This is a pure function – no LLM, no I/O. Safe to call multiple times
    when settings (fps, sync_offset_sec, lookback_sec) change.

    Algorithm (suggested):
      1. If the item has a `spoken_timecode_sec`, use that directly as anchor_sec
         after applying sync_offset_sec. Set anchor_source = "spoken_timecode".
      2. Otherwise compute:
             anchor_sec = segment_start_sec + sync_offset_sec - lookback_sec
         clamp to >= 0. Set anchor_source = "meeting_clock".
      3. If neither is possible, set anchor_sec = None, anchor_source = "none".

    Args:
        items:    FeedbackItems as returned by extract_feedback (anchor_sec may be None).
        settings: Current ProjectSettings for this meeting.

    Returns:
        A new list of FeedbackItems with anchor_sec and anchor_source populated.
        Do NOT mutate the input list.
    """
    raise NotImplementedError
