"""
extraction.py – LLM-powered feedback extraction from transcripts.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Strategy:
  - Chunk long transcripts (~6 000 chars with 500-char overlap) so a 7B model
    never sees a context it cannot handle.
  - The prompt explicitly tells the model to ignore small talk and remarks from
    speakers listed in EDITOR_SPEAKERS (they are NOT the client).
  - Each LLM item is validated with Pydantic; invalid items are dropped.
  - Near-duplicate items (same type + very similar quote) are removed.
  - Stable deterministic IDs are generated from meeting_id + quote hash.
  - spoken_timecode_sec is filled by parse_spoken_time() from the quote text.
  - anchoring.py does the final anchor_sec computation later.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from backend.app import config
from backend.app.anchoring import parse_spoken_time
from backend.app.llm import call_llm_json
from backend.app.models import FeedbackItem, Segment, Transcript

logger = logging.getLogger(__name__)

# ── Chunking constants ────────────────────────────────────────────────────────
# Smaller chunks = more LLM calls, but 3B models extract better from small windows
_CHUNK_CHARS = 1_500
_OVERLAP_CHARS = 300

# ── System prompt ─────────────────────────────────────────────────────────────
_SYSTEM = """\
You are an assistant that extracts ALL client feedback from a video-review call transcript snippet.
You will be given a short exchange. Find EVERY moment where the CLIENT gives feedback.

Rules:
- IGNORE small talk, greetings, pleasantries, and scheduling.
- IGNORE remarks by EDITOR_SPEAKERS — they are the editor, not the client.
- For each feedback moment, create an object with these fields:
  {
    "quote": "<verbatim client words>",
    "note": "<actionable instruction for editor>",
    "type": "change" | "question" | "approval",
    "category": "color" | "sound" | "pacing" | "text_graphics" | "edit" | "other",
    "priority": "high" | "medium" | "low",
    "is_global": true | false,
    "withdrawn": true | false,
    "confidence": <0.0-1.0>,
    "segment_start_sec": <float>,
    "speaker": "<speaker label>"
  }
- "withdrawn" = true if client retracts (e.g. "ignore that", "never mind").
- "is_global" = true only if note applies to entire video.
- "type" = "approval" when client is happy and wants no change.

OUTPUT: Return a JSON object with an "items" array. 
If there is feedback, return it like this:
{
  "items": [
    {"quote":"music is too loud","note":"Lower music volume at 1:30","type":"change","category":"sound","priority":"high","is_global":false,"withdrawn":false,"confidence":0.9,"segment_start_sec":75.0,"speaker":"Client"}
  ]
}

CRITICAL: If there is NO feedback in the snippet (e.g. just greetings or small talk), you MUST output exactly:
{
  "items": []
}

Return ONLY valid JSON. No text, no markdown.
"""

# ── Main entry point ──────────────────────────────────────────────────────────

def extract_feedback(t: Transcript) -> list[FeedbackItem]:
    """
    Use the local LLM to extract client feedback items from a transcript.

    Args:
        t: A fully populated Transcript.

    Returns:
        list[FeedbackItem] with spoken_timecode_sec filled where detectable.
        anchor_sec is NOT yet set; anchoring.py does that.
    """
    if os.getenv("MOCK_LLM", "0") == "1":
        raw_path = Path(__file__).resolve().parents[2] / "samples" / "expected_items.json"
        if raw_path.exists():
            raw = json.loads(raw_path.read_text(encoding="utf-8"))
            return [FeedbackItem.model_validate(item) for item in raw]
        return []

    chunks = _chunk_transcript(t)
    raw_items: list[dict[str, Any]] = []

    logger.info("Processing %d chunks for meeting %s", len(chunks), t.meeting_id)

    for i, chunk_segs in enumerate(chunks):
        prompt = _build_prompt(chunk_segs, t.meeting_id)
        try:
            result = call_llm_json(prompt, system=_SYSTEM)
        except Exception as exc:
            logger.error("LLM call failed for chunk %d: %s", i, exc)
            continue

        if isinstance(result, list):
            logger.info("Chunk %d returned %d items", i, len(result))
            raw_items.extend(result)
        elif isinstance(result, dict):
            # Smaller models sometimes return a single object or wrap in a key
            if "feedback" in result and isinstance(result["feedback"], list):
                raw_items.extend(result["feedback"])
            elif "items" in result and isinstance(result["items"], list):
                raw_items.extend(result["items"])
            else:
                raw_items.append(result)
            logger.info("Chunk %d returned dict (normalized)", i)
        else:
            logger.warning("LLM returned unexpected type for chunk %d: %s", i, type(result))

    logger.info("Total raw items before validation: %d", len(raw_items))
    validated = _validate_items(raw_items, t.meeting_id)
    deduped = _deduplicate(validated)
    logger.info("After validation: %d, after dedup: %d", len(validated), len(deduped))
    return deduped


# ── Chunking ──────────────────────────────────────────────────────────────────

def _chunk_transcript(t: Transcript) -> list[list[Segment]]:
    """
    Chunk by conversational turns instead of fixed character length.
    A chunk consists of a sequence of segments. We want to break the transcript 
    such that each chunk contains at least one non-editor (client) segment, 
    along with the preceding editor segments for context.
    
    This helps small 3B models extract perfectly because they only need to 
    evaluate a single exchange at a time.
    """
    editor_speakers = set(s.strip().lower() for s in config.EDITOR_SPEAKERS)
    
    chunks: list[list[Segment]] = []
    current_chunk: list[Segment] = []
    has_client = False
    
    for seg in t.segments:
        is_editor = bool(seg.speaker and seg.speaker.lower() in editor_speakers)
        
        # If we already have client text in the current chunk, and now the editor is speaking,
        # it means the client's turn is over. Save the current chunk and start a new one.
        # Alternatively, if the current chunk is getting massively long (e.g. client is monologuing),
        # force a break so the LLM doesn't get overwhelmed.
        current_len = sum(len(s.text) for s in current_chunk)
        
        if (is_editor and has_client) or current_len > 1000:
            chunks.append(current_chunk)
            current_chunk = []
            has_client = False
            
        current_chunk.append(seg)
        if not is_editor:
            has_client = True
            
    if current_chunk and has_client:
        chunks.append(current_chunk)
        
    if not chunks and current_chunk:
        chunks.append(current_chunk)
        
    # Group VERY small chunks together (e.g. rapid back and forth under 300 chars)
    # Target chunk size: at least 300 chars, max ~1000 chars.
    merged_chunks = []
    temp_chunk = []
    temp_len = 0
    
    for c in chunks:
        clen = sum(len(s.text) for s in c)
        if temp_len > 0 and temp_len + clen > 1000:
            merged_chunks.append(temp_chunk)
            temp_chunk = list(c)
            temp_len = clen
        else:
            temp_chunk.extend(c)
            temp_len += clen
            # Flush if we hit a minimum viable size so the LLM doesn't get confused by multi-topic chunks
            if temp_len > 300:
                merged_chunks.append(temp_chunk)
                temp_chunk = []
                temp_len = 0

    if temp_chunk:
        merged_chunks.append(temp_chunk)

    return merged_chunks or [[]]


def _build_prompt(segments: list[Segment], meeting_id: str) -> str:
    editor_labels = ", ".join(config.EDITOR_SPEAKERS) or "Priya, Editor, Host"
    segs_json = json.dumps(
        [s.model_dump() for s in segments],
        ensure_ascii=False,
        indent=2,
    )
    return (
        f"Meeting ID: {meeting_id}\n"
        f"EDITOR_SPEAKERS (ignore their remarks): {editor_labels}\n\n"
        f"Extract ALL client feedback from these segments:\n{segs_json}"
    )


# ── Validation ────────────────────────────────────────────────────────────────

def _validate_items(raw: list[dict[str, Any]], meeting_id: str) -> list[FeedbackItem]:
    """
    Validate raw LLM dicts against FeedbackItem schema.
    Drops invalid items and logs warnings.
    Fills in spoken_timecode_sec from the quote text.
    Generates a stable deterministic id.
    """
    valid: list[FeedbackItem] = []
    for i, obj in enumerate(raw):
        if not isinstance(obj, dict):
            logger.warning("Item %d is not a dict; skipping.", i)
            continue
        # Inject required fields that extraction.py controls
        obj.setdefault("meeting_id", meeting_id)
        obj["id"] = _make_id(meeting_id, obj.get("quote", str(i)))
        obj.setdefault("anchor_sec", None)
        obj.setdefault("anchor_source", "none")
        obj.setdefault("needs_review", True)
        obj.setdefault("status", "pending")
        obj.setdefault("spoken_timecode_sec", None)

        # Try to parse spoken timecode from quote
        quote = obj.get("quote", "")
        if quote and obj["spoken_timecode_sec"] is None:
            parsed = parse_spoken_time(quote)
            if parsed is not None:
                obj["spoken_timecode_sec"] = parsed

        try:
            item = FeedbackItem.model_validate(obj)
            valid.append(item)
        except ValidationError as exc:
            logger.warning("Dropping invalid LLM item (quote=%r): %s", quote[:60], exc)

    return valid


def _make_id(meeting_id: str, quote: str) -> str:
    """Stable deterministic ID: sha1(meeting_id + quote)[:12]."""
    h = hashlib.sha1(f"{meeting_id}:{quote}".encode("utf-8")).hexdigest()[:12]
    return f"item-{h}"


# ── Deduplication ─────────────────────────────────────────────────────────────

def _deduplicate(items: list[FeedbackItem]) -> list[FeedbackItem]:
    """
    Remove near-duplicate items: same type + quote that starts with the same
    first 60 characters (handles minor whitespace differences across chunks).
    Keeps the item with higher confidence.
    """
    seen: dict[str, FeedbackItem] = {}
    for item in items:
        key = f"{item.type}:{item.quote[:60].strip().lower()}"
        if key in seen:
            if item.confidence > seen[key].confidence:
                seen[key] = item
        else:
            seen[key] = item
    return list(seen.values())
