"""
extraction.py – LLM-powered feedback extraction from transcripts.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.
"""
from backend.app.models import FeedbackItem, Transcript


def extract_feedback(t: Transcript) -> list[FeedbackItem]:
    """
    Use the local LLM to extract client feedback items from a transcript.

    Each item should have:
      - A verbatim `quote` from the client.
      - A short, actionable `note`.
      - A `type` (change / question / approval).
      - A `category` (color / sound / pacing / text_graphics / edit / other).
      - A `priority` (high / medium / low).
      - `segment_start_sec` copied from the matching Segment.
      - `confidence` 0..1 reflecting the LLM's certainty.
      - `needs_review=True` for confidence < 0.8.

    Args:
        t: A fully populated Transcript.

    Returns:
        A list of FeedbackItem objects (anchor_sec NOT yet set; anchoring.py does that).
    """
    raise NotImplementedError
