"""
ingest.py – Webhook handling and transcript import.
Owned by KARTHIK. Sreedhar: do not edit this file.
"""
from backend.app.models import Transcript


def handle_summary_completed(event: dict) -> None:
    """
    Handle a Meetily `summary.completed` webhook event.

    Flow:
        1. Extract meeting_id from event payload.
        2. Call meetily_client.get_transcript(meeting_id).
        3. Call store.save_transcript(transcript).
        4. Call pipeline.process_transcript(transcript, settings).
        5. Call store.save_items(meeting_id, items).

    Args:
        event: The parsed webhook payload dict.
    """
    raise NotImplementedError


def parse_uploaded_transcript(filename: str, content: bytes) -> Transcript:
    """
    Parse a manually uploaded transcript file into a Transcript model.

    Supports .json (Meetily export format) and plain .txt (one line per segment).

    Args:
        filename: Original filename (used to detect format by extension).
        content:  Raw file bytes.

    Returns:
        A Transcript object ready for the pipeline.
    """
    raise NotImplementedError
