"""
ingest.py – Webhook handling and transcript import.
Owned by KARTHIK. Sreedhar: do not edit this file.

handle_summary_completed: fetch transcript -> store -> pipeline -> store items
parse_uploaded_transcript: parse uploaded files into Transcript
"""
import json
import re
import uuid

from backend.app import config, store
from backend.app.models import Segment, Transcript


def handle_summary_completed(event: dict) -> None:
    """
    Handle a Meetily `summary.completed` webhook event.

    Flow:
        1. Extract meeting_id from event payload.
        2. Call meetily_client.get_transcript(meeting_id).
        3. Call store.save_transcript(transcript).
        4. Call pipeline.process_transcript(transcript, settings).
        5. Call store.save_items(meeting_id, items).

    Args:
        event: The parsed webhook payload dict.
    """
    from backend.app import meetily_client, pipeline

    # The event envelope: resource.id is the meeting_id for summary.completed
    # Also check for meeting_id at top level (may be present in some envelopes)
    resource = event.get("resource", {})
    meeting_id = event.get("meeting_id") or resource.get("id", "")

    if not meeting_id:
        raise ValueError("No meeting_id found in event payload")

    # 1. Fetch transcript from Meetily API
    transcript = meetily_client.get_transcript(meeting_id)

    # 2. Store transcript
    store.save_transcript(transcript)

    # 3. Run pipeline (extract feedback + anchor)
    settings = store.get_settings(meeting_id)
    items = pipeline.process_transcript(transcript, settings)

    # 4. Store items
    store.save_items(meeting_id, items)


def parse_uploaded_transcript(filename: str, content: bytes) -> Transcript:
    """
    Parse a manually uploaded transcript file into a Transcript model.

    Supports:
      - .json: Meetily export JSON format, or our own Transcript JSON format
      - .md / .markdown: Meetily markdown export
      - .txt: Plain text with timestamped lines like:
        [00:01:24] Speaker: text
        00:01:24 Speaker: text

    Args:
        filename: Original filename (used to detect format by extension).
        content:  Raw file bytes.

    Returns:
        A Transcript object ready for the pipeline.
    """
    text = content.decode("utf-8", errors="replace")
    lower_name = filename.lower()
    meeting_id = f"upload-{uuid.uuid4().hex[:12]}"

    if lower_name.endswith(".json"):
        return _parse_json_transcript(text, meeting_id)
    elif lower_name.endswith((".md", ".markdown")):
        return _parse_markdown_transcript(text, meeting_id)
    else:
        # Default: treat as plain text
        return _parse_text_transcript(text, meeting_id)


def _parse_json_transcript(text: str, meeting_id: str) -> Transcript:
    """Parse a JSON transcript (Meetily export or our format)."""
    data = json.loads(text)

    # If it looks like our Transcript format (has meeting_id + segments)
    if "segments" in data and isinstance(data["segments"], list):
        # Re-use the meeting_id from the file if present
        mid = data.get("meeting_id", meeting_id)
        segments = []
        for seg in data["segments"]:
            segments.append(Segment(
                start_sec=float(seg.get("start_sec", seg.get("start", 0))),
                end_sec=_safe_float(seg.get("end_sec", seg.get("end"))),
                speaker=seg.get("speaker"),
                text=seg.get("text", ""),
            ))
        return Transcript(
            meeting_id=mid,
            title=data.get("title"),
            segments=segments,
            summary=data.get("summary"),
        )

    # Meetily ExportDto format: { meeting: {id, title, ...}, transcript: {segments: [...]}, summary: ... }
    if "transcript" in data and isinstance(data["transcript"], dict):
        meeting_info = data.get("meeting", {})
        mid = meeting_info.get("id", meeting_id)
        title = meeting_info.get("title")
        transcript_data = data["transcript"]
        segments = []
        for seg in transcript_data.get("segments", []):
            segments.append(Segment(
                start_sec=float(seg.get("start_sec", seg.get("start", seg.get("timestamp", 0)))),
                end_sec=_safe_float(seg.get("end_sec", seg.get("end"))),
                speaker=seg.get("speaker") or seg.get("speaker_label"),
                text=seg.get("text", ""),
            ))
        summary_text = None
        summary_data = data.get("summary")
        if isinstance(summary_data, str):
            summary_text = summary_data
        elif isinstance(summary_data, dict):
            summary_text = summary_data.get("result") or summary_data.get("text")
        return Transcript(
            meeting_id=mid,
            title=title,
            segments=segments,
            summary=summary_text,
        )

    raise ValueError(f"Unrecognized JSON format – no 'segments' or 'transcript' key found")


def _parse_markdown_transcript(text: str, meeting_id: str) -> Transcript:
    """Parse a Meetily markdown export into a Transcript."""
    lines = text.strip().split("\n")
    title = None
    segments: list[Segment] = []

    # Try to extract title from first heading
    for line in lines:
        if line.startswith("# "):
            title = line[2:].strip()
            break

    # Parse timestamped lines
    for line in lines:
        seg = _parse_timestamped_line(line)
        if seg:
            segments.append(seg)

    return Transcript(
        meeting_id=meeting_id,
        title=title,
        segments=segments,
    )


def _parse_text_transcript(text: str, meeting_id: str) -> Transcript:
    """Parse a plain text transcript with timestamped lines."""
    lines = text.strip().split("\n")
    segments: list[Segment] = []
    standalone_timestamp = re.compile(r"^\[?(\d{1,2}:\d{2}(?::\d{2})?)\]?$")
    standalone_speaker = re.compile(r"^(?:speaker\s+\w+|host|editor|client|director|reviewer):?$", re.IGNORECASE)

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        timestamp_match = standalone_timestamp.fullmatch(line)
        if timestamp_match:
            timestamp_parts = timestamp_match.group(1).split(":")
            if len(timestamp_parts) == 3:
                hours, minutes, seconds = timestamp_parts
                start_sec = int(hours) * 3600 + int(minutes) * 60 + float(seconds)
            else:
                minutes, seconds = timestamp_parts
                start_sec = int(minutes) * 60 + float(seconds)

            i += 1
            while i < len(lines) and not lines[i].strip():
                i += 1

            speaker = None
            if i < len(lines):
                speaker_line = lines[i].strip()
                if standalone_speaker.fullmatch(speaker_line):
                    speaker = speaker_line.rstrip(":").strip()
                    i += 1
                    while i < len(lines) and not lines[i].strip():
                        i += 1

            body_lines = []
            while i < len(lines) and not standalone_timestamp.fullmatch(lines[i].strip()):
                if lines[i].strip():
                    body_lines.append(lines[i].strip())
                i += 1
            body = " ".join(body_lines)
            if body:
                segments.append(Segment(start_sec=start_sec, speaker=speaker, text=body))
            continue

        seg = _parse_timestamped_line(line)
        if seg:
            segments.append(seg)
        i += 1

    return Transcript(
        meeting_id=meeting_id,
        segments=segments,
    )


# Pattern: [HH:MM:SS] or HH:MM:SS or [MM:SS] or MM:SS, optionally followed by Speaker: text
_TS_PATTERN = re.compile(
    r"^\[?(\d{1,2}:\d{2}(?::\d{2})?)\]?\s*"  # timestamp in optional brackets
    r"(?:([^:]+?):\s*)?"                         # optional speaker label
    r"(.+)$"                                     # text
)


def _parse_timestamped_line(line: str) -> Segment | None:
    """Try to parse a single timestamped line into a Segment."""
    line = line.strip()
    if not line or line.startswith("#"):
        return None

    match = _TS_PATTERN.match(line)
    if not match:
        return None

    timestamp_str, speaker, text = match.groups()

    # Parse timestamp to seconds
    parts = timestamp_str.split(":")
    if len(parts) == 3:
        h, m, s = parts
        total_sec = int(h) * 3600 + int(m) * 60 + float(s)
    elif len(parts) == 2:
        m, s = parts
        total_sec = int(m) * 60 + float(s)
    else:
        return None

    return Segment(
        start_sec=total_sec,
        speaker=speaker.strip() if speaker else None,
        text=text.strip(),
    )


def _safe_float(val) -> float | None:
    """Convert a value to float, or return None."""
    if val is None:
        return None
    try:
        return float(val)
    except (ValueError, TypeError):
        return None
