"""
llm.py – Local LLM (Ollama) interface.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Supports:
  - JSON-mode requests to Ollama's /api/chat endpoint
  - MOCK_LLM=1: returns samples/expected_items.json without calling Ollama
  - Timeout + single retry with a "fix your JSON" follow-up prompt
"""
import json
import logging
import os
from pathlib import Path

import httpx

from backend.app import config

logger = logging.getLogger(__name__)

# ── Constants ────────────────────────────────────────────────────────────────
_TIMEOUT = 120  # seconds; 7B models can be slow on CPU
_SAMPLES_PATH = Path(__file__).resolve().parents[2] / "samples" / "expected_items.json"

# ── Public API ────────────────────────────────────────────────────────────────

def call_llm(prompt: str, system: str = "", json_mode: bool = True) -> str:
    """
    Send a prompt to the locally running Ollama instance and return the
    response text.

    Args:
        prompt:    The user-turn prompt string to send.
        system:    Optional system message (instructions / persona).
        json_mode: If True, requests JSON-formatted output from the model.

    Returns:
        The model's response as a plain string.

    Raises:
        RuntimeError: if Ollama is unavailable, returns an error, or
                      JSON repair also fails.
    """
    if os.getenv("MOCK_LLM", "0") == "1":
        # ── MOCK path ────────────────────────────────────────────────────────
        logger.info("MOCK_LLM=1 – returning samples/expected_items.json")
        if _SAMPLES_PATH.exists():
            return _SAMPLES_PATH.read_text(encoding="utf-8")
        return "[]"

    return _call_ollama(prompt, system, json_mode)


# ── Internal helpers ──────────────────────────────────────────────────────────

def _build_messages(prompt: str, system: str) -> list[dict]:
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})
    return messages


def _call_ollama(prompt: str, system: str, json_mode: bool) -> str:
    """One attempt to call Ollama; raises RuntimeError on failure."""
    url = f"{config.OLLAMA_URL.rstrip('/')}/api/chat"
    payload: dict = {
        "model": config.OLLAMA_MODEL,
        "messages": _build_messages(prompt, system),
        "stream": False,
    }
    if json_mode:
        payload["format"] = "json"

    logger.debug("Calling Ollama: model=%s url=%s", config.OLLAMA_MODEL, url)

    try:
        resp = httpx.post(url, json=payload, timeout=_TIMEOUT)
        resp.raise_for_status()
    except httpx.HTTPStatusError as exc:
        raise RuntimeError(f"Ollama HTTP error {exc.response.status_code}: {exc.response.text}") from exc
    except httpx.RequestError as exc:
        raise RuntimeError(f"Ollama connection error: {exc}") from exc

    data = resp.json()
    text: str = data.get("message", {}).get("content", "")

    if not text.strip():
        raise RuntimeError("Ollama returned an empty response.")

    return text


def call_llm_json(prompt: str, system: str = "") -> list | dict:
    """
    Convenience wrapper: calls call_llm in JSON mode, parses the result.
    On parse failure, retries once with a "fix your JSON" follow-up.

    Returns:
        Parsed Python object (list or dict).

    Raises:
        RuntimeError: if both attempts fail to produce valid JSON.
    """
    if os.getenv("MOCK_LLM", "0") == "1":
        raw = call_llm(prompt, system, json_mode=True)
        return json.loads(raw)

    # ── Attempt 1 ────────────────────────────────────────────────────────────
    raw = _call_ollama(prompt, system, json_mode=True)
    try:
        result = _parse_json(raw)
        return _normalize_result(result)
    except ValueError as first_err:
        logger.warning("Ollama returned invalid JSON on first attempt: %s. Retrying…", first_err)

    # ── Attempt 2 – "fix your JSON" follow-up ────────────────────────────────
    fix_prompt = (
        "Your previous response was not valid JSON. "
        "Return ONLY the corrected JSON object with no extra text, markdown, or explanation.\n\n"
        f"Bad response:\n{raw}"
    )
    raw2 = _call_ollama(fix_prompt, system="", json_mode=True)
    try:
        result = _parse_json(raw2)
        return _normalize_result(result)
    except ValueError as second_err:
        raise RuntimeError(
            f"Ollama returned invalid JSON after retry. "
            f"First error: {first_err}. Second error: {second_err}.\n"
            f"Last response: {raw2[:500]}"
        ) from second_err


def _normalize_result(result):
    """
    Smaller models often return a single dict or wrap items in a key.
    Normalize to always return a list of item dicts.
    """
    if isinstance(result, list):
        return result
    if isinstance(result, dict):
        if not result:
            return []
        # Check if the dict wraps a list under a known key
        for key in ("feedback", "items", "results", "data"):
            if key in result and isinstance(result[key], list):
                return result[key]
        # It's a single item dict — wrap it
        return [result]
    return result


def _parse_json(text: str) -> list | dict:
    """Strip markdown fences then parse JSON; raises ValueError on failure."""
    stripped = text.strip()
    # Remove ```json ... ``` or ``` ... ``` fences if present
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        stripped = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    return json.loads(stripped)
