"""
llm.py – Local LLM (Ollama) interface.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.
"""


def call_llm(prompt: str, schema: dict | None = None) -> str:
    """
    Send a prompt to the locally running Ollama instance and return the response text.

    Args:
        prompt: The full prompt string to send.
        schema: Optional JSON schema for structured/JSON-mode output.

    Returns:
        The model's response as a plain string.

    Raises:
        RuntimeError: if Ollama is unavailable or returns an error.
    """
    raise NotImplementedError
