"""
meetily_client.py – Meetily Pro Automation API client.
Owned by KARTHIK. Sreedhar: do not edit this file.
"""
from backend.app.models import Transcript


def get_transcript(meeting_id: str) -> Transcript:
    """
    Fetch the timestamped transcript for a meeting from the Meetily API.

    Args:
        meeting_id: The Meetily meeting identifier.

    Returns:
        A Transcript object with all segments.

    Raises:
        httpx.HTTPStatusError: if the API returns a non-2xx response.
    """
    raise NotImplementedError


def list_meetings() -> list[dict]:
    """
    List all meetings available via the Meetily API.

    Returns:
        A list of meeting dicts as returned by the Meetily API.
    """
    raise NotImplementedError
