"""
meetily_client.py – Meetily Pro Automation API client.
Owned by KARTHIK. Sreedhar: do not edit this file.

Uses httpx with the API key from env.
Endpoints are based on the Meetily docs (api-reference, TranscriptResponse).
"""
import httpx

from backend.app import config
from backend.app.models import Segment, Transcript


def _client() -> httpx.Client:
    """Create a configured httpx client for Meetily API calls."""
    return httpx.Client(
        base_url=config.MEETILY_BASE_URL,
        headers={"Authorization": f"Bearer {config.MEETILY_API_KEY}"},
        timeout=30.0,
    )


def is_reachable() -> bool:
    """Check if the Meetily API is reachable (GET /health)."""
    try:
        with _client() as client:
            resp = client.get("/health")
            return resp.status_code == 200
    except (httpx.ConnectError, httpx.TimeoutException):
        return False


def list_meetings() -> list[dict]:
    """
    List all meetings available via the Meetily API.

    Returns:
        A list of meeting dicts as returned by the Meetily API.
    """
    with _client() as client:
        resp = client.get("/v1/meetings", params={"limit": 200})
        resp.raise_for_status()
        data = resp.json()
        return data.get("meetings", [])


def get_transcript(meeting_id: str) -> Transcript:
    """
    Fetch the timestamped transcript for a meeting from the Meetily API.

    The Meetily TranscriptResponse has:
      meeting_id, title, segments (list of TranscriptSegmentDto).

    We normalize into our Transcript / Segment models.

    Args:
        meeting_id: The Meetily meeting identifier.

    Returns:
        A Transcript object with all segments.

    Raises:
        httpx.HTTPStatusError: if the API returns a non-2xx response.
    """
    with _client() as client:
        resp = client.get(f"/v1/meetings/{meeting_id}/transcript")
        resp.raise_for_status()
        data = resp.json()

    # Also fetch the summary if available
    summary_text = None
    try:
        with _client() as client:
            summary_resp = client.get(f"/v1/meetings/{meeting_id}/summary")
            if summary_resp.status_code == 200:
                summary_data = summary_resp.json()
                summary_text = summary_data.get("result")
    except Exception:
        pass  # Summary is optional

    # Normalize Meetily's segment shape into our Segment model.
    # Real Meetily API fields (confirmed from live API):
    #   audio_start_time, audio_end_time (seconds as float)
    #   speaker: "mic" (local mic) or "system" (remote audio)
    #   text, timestamp (wall-clock string), words[]
    segments = []
    for seg in data.get("segments", []):
        segments.append(Segment(
            start_sec=_extract_start_sec(seg),
            end_sec=_extract_end_sec(seg),
            speaker=_normalize_speaker(seg.get("speaker")),
            text=seg.get("text", ""),
        ))

    return Transcript(
        meeting_id=data.get("meeting_id", meeting_id),
        title=data.get("title"),
        segments=segments,
        summary=summary_text,
    )


def _normalize_speaker(speaker: object) -> str | None:
    """Normalize speaker field from Meetily segment."""
    if not speaker:
        return None
    return str(speaker).strip()


def _extract_start_sec(seg: dict) -> float:
    """Extract start time in seconds from a Meetily segment dict."""
    for key in ("audio_start_time", "start_sec", "start", "start_time", "start_ms"):
        val = seg.get(key)
        if val is not None:
            try:
                if "ms" in key:
                    return float(val) / 1000.0
                return float(val)
            except (ValueError, TypeError):
                continue
    ts = seg.get("timestamp")
    if ts and isinstance(ts, str):
        parts = ts.split(":")
        try:
            if len(parts) == 3:
                return float(parts[0]) * 3600 + float(parts[1]) * 60 + float(parts[2])
            elif len(parts) == 2:
                return float(parts[0]) * 60 + float(parts[1])
        except (ValueError, TypeError):
            pass
    return 0.0


def _extract_end_sec(seg: dict) -> float | None:
    """Extract end time in seconds from a Meetily segment dict."""
    for key in ("audio_end_time", "end_sec", "end", "end_time", "end_ms"):
        val = seg.get(key)
        if val is not None:
            try:
                if "ms" in key:
                    return float(val) / 1000.0
                return float(val)
            except (ValueError, TypeError):
                continue
    return None


def list_webhooks() -> list[dict]:
    """List all registered webhooks via the Meetily API."""
    with _client() as client:
        resp = client.get("/v1/webhooks")
        resp.raise_for_status()
        return resp.json()


def register_webhook(url: str, events: list[str], delivery_mode: str = "at-least-once") -> dict:
    """
    Register a webhook with the Meetily API.
    Returns the full response including hmac_secret (shown only once).
    """
    with _client() as client:
        resp = client.post("/v1/webhooks", json={
            "url": url,
            "events": events,
            "delivery_mode": delivery_mode,
        })
        resp.raise_for_status()
        return resp.json()
