"""
pipeline.py – Full extraction + anchoring pipeline.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Special behaviour when MOCK_LLM=1:
  Returns items loaded from samples/expected_items.json so the whole app
  can run without Ollama during development.
"""
import json
import os
from pathlib import Path

from backend.app.models import FeedbackItem, ProjectSettings, Transcript


def process_transcript(
    t: Transcript, settings: ProjectSettings
) -> list[FeedbackItem]:
    """
    Run the full pipeline: extract feedback items from the transcript, then
    anchor each item to a video timecode using the project settings.

    When the env var MOCK_LLM=1 this function loads items from
    `samples/expected_items.json` (relative to the repo root) and returns
    them immediately without calling the LLM or anchoring.

    Args:
        t:        A populated Transcript.
        settings: Current ProjectSettings for this meeting.

    Returns:
        A list of fully populated FeedbackItems with anchor_sec set.
    """
    # ── MOCK path ──────────────────────────────────────────────────────────
    if os.getenv("MOCK_LLM", "0") == "1":
        samples_path = Path(__file__).resolve().parents[2] / "samples" / "expected_items.json"
        if samples_path.exists():
            raw = json.loads(samples_path.read_text(encoding="utf-8"))
            return [FeedbackItem.model_validate(item) for item in raw]
        # If file doesn't exist yet, return an empty list rather than crash
        return []

    # ── Real path (Sivapriyan implements this) ─────────────────────────────
    raise NotImplementedError
