"""
pipeline.py – Full extraction + anchoring pipeline.
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Special behaviour when MOCK_LLM=1:
  Returns items loaded from samples/expected_items.json so the whole app
  can run without Ollama during development.
"""
import json
import os
from pathlib import Path

from backend.app.anchoring import anchor_items
from backend.app.extraction import extract_feedback
from backend.app.models import FeedbackItem, ProjectSettings, Transcript


def process_transcript(
    t: Transcript, settings: ProjectSettings
) -> list[FeedbackItem]:
    # ── MOCK path ──────────────────────────────────────────────────────────
    if os.getenv("MOCK_LLM", "0") == "1":
        samples_path = (
            Path(__file__).resolve().parents[2] / "samples" / "expected_items.json"
        )
        if samples_path.exists():
            raw = json.loads(samples_path.read_text(encoding="utf-8"))
            items = []
            for item in raw:
                fi = FeedbackItem.model_validate(item)
                fi.id = f"{t.meeting_id}-{fi.id}"
                items.append(fi)
            return items
        # If file doesn't exist yet, return an empty list rather than crash
        return []

    # ── Real path ──────────────────────────────────────────────────────────
    items = extract_feedback(t)
    return anchor_items(items, settings)
