"""
redaction.py – Safe transcript redaction (removes sensitive PII from transcript text).
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.
"""
from backend.app.models import Transcript


def redact_transcript(t: Transcript) -> Transcript:
    """
    Return a copy of the transcript with PII / sensitive content redacted.

    Redaction strategy is up to Sivapriyan. Suggested approach:
      - Replace names, emails, phone numbers, account numbers with [REDACTED].
      - Do NOT modify segment timestamps or speaker labels.
      - Return a NEW Transcript object; do not mutate the input.

    Args:
        t: The original Transcript.

    Returns:
        A redacted copy of the Transcript.
    """
    raise NotImplementedError
