"""
redaction.py – Safe transcript redaction (removes PII from transcript text).
Owned by SIVAPRIYAN. Sreedhar: do not edit this file.

Strategy:
  - Regex patterns for emails, phone numbers, money amounts.
  - Simple heuristic for proper names: Title-case words not in a common
    stop-list, appearing after name-trigger words ("my name is", "I'm", etc.)
    OR the speaker label itself.
  - Uses spaCy NER for person/org names if spaCy is installed; falls back
    gracefully to the heuristic if not.
  - Consistent placeholder numbering per category: [Email 1], [Phone 1],
    [Amount 1], [Person A], [Person B] …
  - The mapping (placeholder -> original) stays local; never serialised out.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable

from backend.app.models import Segment, Transcript

# ── Try to import spaCy (optional) ────────────────────────────────────────────
try:
    import spacy as _spacy  # type: ignore

    _nlp = _spacy.load("en_core_web_sm")
    _SPACY_AVAILABLE = True
except Exception:  # noqa: BLE001
    _nlp = None
    _SPACY_AVAILABLE = False


# ── Data contracts ────────────────────────────────────────────────────────────

@dataclass
class RedactionResult:
    """
    Holds the redacted text plus the mapping from placeholder -> original value.
    The mapping must NEVER leave the local machine.
    """
    text: str
    mapping: dict[str, str] = field(default_factory=dict)


# ── Regex patterns ─────────────────────────────────────────────────────────────

_EMAIL_RE = re.compile(
    r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}",
    re.IGNORECASE,
)

_PHONE_RE = re.compile(
    r"""
    (?:plus[-\s]?|[+])?               # optional leading +
    (?:\d{1,3}[-\s]?)?                # optional country code
    (?:\(?\d{2,4}\)?[-\s]?)           # area code
    \d{2,4}[-\s]?\d{2,4}             # number body
    (?:[-\s]?\d{2,4})?               # optional suffix
    """,
    re.VERBOSE,
)

_MONEY_RE = re.compile(
    r"""
    (?:
        [$£€₹]\s*\d[\d,]*(?:\.\d{1,2})?   # symbol-first: $15,000
      | \d[\d,]*(?:\.\d{1,2})?\s*(?:dollars?|rupees?|USD|INR|EUR|GBP)  # amount-first
      | (?:fifteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million)
        (?:\s+(?:thousand|hundred|million))?
        \s+(?:dollars?|rupees?|USD|INR)     # word amounts: "fifteen thousand dollars"
    )
    """,
    re.VERBOSE | re.IGNORECASE,
)

# Simple heuristic: trigger phrases that precede names
_NAME_TRIGGER_RE = re.compile(
    r"""
    (?:
        my\s+(?:CEO|boss|client|colleague|manager|director|partner|friend|contact|name\s+is)\s+
      | I\s+am\s+
      | I'm\s+
      | his\s+name\s+is\s+
      | her\s+name\s+is\s+
      | this\s+is\s+
    )
    ([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)   # Title-case name(s)
    """,
    re.VERBOSE,
)


# ── Counters / state per redact() call ────────────────────────────────────────

class _Counters:
    def __init__(self) -> None:
        self._counts: dict[str, int] = {}
        self._seen: dict[str, str] = {}  # original -> placeholder

    def placeholder(self, category: str, original: str, alpha: bool = False) -> str:
        """Return a consistent placeholder for `original` in `category`."""
        key = f"{category}:{original.lower().strip()}"
        if key in self._seen:
            return self._seen[key]
        n = self._counts.get(category, 0) + 1
        self._counts[category] = n
        label = chr(64 + n) if alpha else str(n)  # A, B, C … or 1, 2, 3 …
        ph = f"[{category} {label}]"
        self._seen[key] = ph
        return ph


# ── Core redaction logic ───────────────────────────────────────────────────────

def redact(text: str) -> RedactionResult:
    """
    Redact a single string of text.

    Replacements (consistent across calls to the same function invocation):
      - Emails   -> [Email 1], [Email 2] …
      - Phones   -> [Phone 1], [Phone 2] …
      - Amounts  -> [Amount 1], [Amount 2] …
      - Names    -> [Person A], [Person B] …

    Returns:
        RedactionResult with redacted text and the placeholder->original mapping.
    """
    counters = _Counters()
    mapping: dict[str, str] = {}

    def _replace(pattern: re.Pattern, cat: str, alpha: bool = False) -> Callable[[re.Match], str]:
        def _inner(m: re.Match) -> str:
            original = m.group(0)
            ph = counters.placeholder(cat, original, alpha=alpha)
            mapping[ph] = original
            return ph
        return _inner

    # Order matters: emails before phones (emails contain @, not confused)
    text = _EMAIL_RE.sub(_replace(_EMAIL_RE, "Email"), text)
    text = _PHONE_RE.sub(_replace(_PHONE_RE, "Phone"), text)
    text = _MONEY_RE.sub(_replace(_MONEY_RE, "Amount"), text)
    text = _redact_names(text, counters, mapping)

    return RedactionResult(text=text, mapping=mapping)


def _redact_names(text: str, counters: _Counters, mapping: dict[str, str]) -> str:
    """Redact person names using spaCy if available, else heuristic."""
    if _SPACY_AVAILABLE and _nlp is not None:
        return _redact_names_spacy(text, counters, mapping)
    return _redact_names_heuristic(text, counters, mapping)


def _redact_names_spacy(text: str, counters: _Counters, mapping: dict[str, str]) -> str:
    doc = _nlp(text)
    spans = sorted(
        [ent for ent in doc.ents if ent.label_ in ("PERSON", "ORG")],
        key=lambda e: e.start_char,
        reverse=True,  # replace right-to-left to preserve offsets
    )
    for ent in spans:
        ph = counters.placeholder("Person", ent.text, alpha=True)
        mapping[ph] = ent.text
        text = text[: ent.start_char] + ph + text[ent.end_char :]
    return text


def _redact_names_heuristic(text: str, counters: _Counters, mapping: dict[str, str]) -> str:
    """Replace names found after trigger phrases."""
    def _inner(m: re.Match) -> str:
        name = m.group(1)
        ph = counters.placeholder("Person", name, alpha=True)
        mapping[ph] = name
        # Keep the trigger phrase, replace only the name
        full = m.group(0)
        return full[: full.rfind(name)] + ph

    return _NAME_TRIGGER_RE.sub(_inner, text)


def restore(text: str, mapping: dict[str, str]) -> str:
    """
    Reverse a redaction by replacing placeholders with their original values.

    Args:
        text:    The redacted text.
        mapping: The mapping returned by redact() (placeholder -> original).

    Returns:
        The original text with all placeholders restored.
    """
    for placeholder, original in mapping.items():
        text = text.replace(placeholder, original)
    return text


# ── Transcript-level helpers ───────────────────────────────────────────────────

def redact_transcript(t: Transcript) -> tuple[Transcript, dict[str, str]]:
    """
    Return a redacted copy of the transcript plus a combined mapping.

    The mapping covers all segments. Speaker labels are preserved.
    Timestamps are NOT modified.

    Args:
        t: The original Transcript.

    Returns:
        (redacted_transcript, combined_mapping)
    """
    combined_mapping: dict[str, str] = {}
    new_segments: list[Segment] = []

    for seg in t.segments:
        result = redact(seg.text)
        combined_mapping.update(result.mapping)
        new_segments.append(
            Segment(
                start_sec=seg.start_sec,
                end_sec=seg.end_sec,
                speaker=seg.speaker,
                text=result.text,
            )
        )

    redacted_t = Transcript(
        meeting_id=t.meeting_id,
        title=t.title,
        summary=t.summary,
        segments=new_segments,
    )
    return redacted_t, combined_mapping
